/*
Step 4: Treatment Comparisons of top 3 model generated treatments for the patient
ML-Model Predictions for the Case Studies
- Case Studies A,B,C,D
- Predicition represents the prediction with the highest confidence percentage
- Probabilites represents the confidence precentages for all the possible prediciton outcomes
- Options delivers the top 3 recommendations and the features that contributed to the prediction including their weight

*/

import { PageHeader } from "../components/layout/PageHeader";
import { StepFooter } from "../components/layout/StepFooter";

import { useEffect, useState } from "react";

import { useWorkflow } from "../context/WorkflowContext";

import { fetchCase } from "../services/caseService";

import {
  fetchTreatmentRecommendations,
  type TreatmentPrediction,
} from "../services/predictionService";

function ProbabilityBar({ value }: { value: number }) {
  return (
    <div>
      <div className="probability-row">
        <div className="probability-track">
          <div
            className="probability-fill"
            style={{
              width: `${value}%`,
            }}
          />
        </div>
        <span>{value}%</span>
      </div>
      <small className="muted">
        Estimated likelihood that this option is preferred by the model.
      </small>
    </div>
  );
}

function ShapChart({
  shap,
}: {
  shap: {
    feature: string;
    value: number;
  }[];
}) {
  const visibleShap = shap.filter((feature) => Number(feature.value.toFixed(2)) !== 0);
  if (visibleShap.length === 0) {
    return <p className="muted">No meaningful model factors to display.</p>;
  }

  const max = Math.max(...visibleShap.map((f) => Math.abs(f.value)));

  return (
    <div className="shap-chart">
      {visibleShap.map((feature) => (
        <div className="shap-row" key={feature.feature}>
          <div className="shap-label">{feature.feature}</div>

          <div className="shap-track">
            <div
              className={feature.value >= 0 ? "shap-positive" : "shap-negative"}
              style={{
                width: `${(Math.abs(feature.value) / max) * 100}%`,
              }}
            />
          </div>

          <span>
            {feature.value > 0 ? "+" : ""}
            {feature.value.toFixed(2)}
          </span>
        </div>
      ))}
    </div>
  );
}

export function TreatmentComparison() {
  const { selectedPatientId } = useWorkflow();
  const [prediction, setPrediction] = useState<TreatmentPrediction | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;

    async function loadPrediction() {
      setLoading(true);
      setError(null);

      if (!selectedPatientId) {
        setPrediction(null);
        setLoading(false);
        return;
      }

      try {
        const patient = await fetchCase(selectedPatientId);
        if (!patient || !active) return;

        const result = await fetchTreatmentRecommendations(patient);
        if (active) {
          setPrediction(result);
        }
      } catch (err) {
        if (active) {
          const message = err instanceof Error ? err.message : "Failed to load treatment recommendations.";
          setError(message);
        }
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    }

    void loadPrediction();

    return () => {
      active = false;
    };
  }, [selectedPatientId]);

  if (loading) {
    return (
      <div className="page">
        <PageHeader title="AI Treatment Recommendations" badge="Step 4" />
        <p className="muted">Loading recommendations...</p>
      </div>
    );
  }

  return (
    <div className="page">
      <PageHeader title="AI Treatment Recommendations" badge="Step 4" />

      <div className="recommendation-notice">
        <strong>Decision Support Only</strong>
        <p>
          These recommendations are generated by the machine learning model and should be interpreted alongside clinical judgement.
        </p>
      </div>

      {error ? <p className="muted">{error}</p> : null}

      {!error && prediction ? (
        <div className="recommendations-grid">
          {prediction.recommendations.map((treatment, index) => (
            <div key={treatment.id} className="recommendation-card">
              <div className="recommendation-header">
                <strong>
                  {index + 1}. {treatment.name}
                </strong>
              </div>

              <ProbabilityBar value={treatment.probability} />

              <h3>Model Explanation</h3>
              <ShapChart shap={treatment.shap} />
            </div>
          ))}
        </div>
      ) : null}

      <StepFooter />
    </div>
  );
}