import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { mockTreatmentOptions, getAssessmentTreatmentLabel } from '../data/mockData';
import { useWorkflow } from '../context/WorkflowContext';
import { PageHeader } from '../components/layout/PageHeader';
import { StepFooter } from '../components/layout/StepFooter';
export function TreatmentComparison() {
    const { assessment, recordInteraction } = useWorkflow();
    const [expandedCards, setExpandedCards] = useState({});
    const toggleExpand = (id) => {
        setExpandedCards((prev) => ({ ...prev, [id]: !prev[id] }));
    };
    return (_jsxs("div", { className: "page", children: [_jsx(PageHeader, { title: "Treatment Options Comparison", badge: "Step 4" }), assessment && (_jsx("div", { className: "card card-sm", style: { marginBottom: '0.75rem' }, children: _jsxs("p", { style: { margin: 0, fontSize: '0.85rem' }, children: ["Your initial selection: ", _jsx("strong", { children: getAssessmentTreatmentLabel(assessment.selectedTreatment) })] }) })), _jsx("div", { className: "treatment-comparison-grid", children: mockTreatmentOptions.map((opt) => (_jsxs("div", { className: `card treatment-option-card ${assessment?.selectedTreatment === opt.id ? 'selected' : ''}`, onClick: () => recordInteraction({ type: 'treatment_view', payload: opt.id }), children: [_jsxs("div", { className: "treatment-header", children: [_jsx("h4", { children: opt.name }), _jsxs("div", { className: "treatment-badges", children: [_jsx("span", { className: "strength-badge", children: opt.strength }), _jsx("span", { className: `uncertainty-badge uncertainty-${opt.uncertainty}`, children: opt.uncertainty.toUpperCase() })] })] }), _jsxs("p", { className: "evidence-strength-label", children: ["Evidence: ", opt.evidenceStrength] }), _jsxs("div", { className: "treatment-cols", children: [_jsxs("div", { className: "treatment-section", children: [_jsx("h5", { children: "Benefits" }), _jsx("ul", { children: opt.benefits.map((b, i) => _jsx("li", { children: b }, i)) })] }), _jsxs("div", { className: "treatment-section", children: [_jsx("h5", { children: "Risks" }), _jsx("ul", { children: opt.risks.map((r, i) => _jsx("li", { children: r }, i)) })] })] }), _jsxs("div", { className: "treatment-meta", children: [_jsx("div", { children: _jsxs("p", { className: "meta-text", children: [_jsx("strong", { children: "QoL:" }), " ", opt.qolImpact] }) }), _jsx("div", { children: _jsxs("p", { className: "meta-text", children: [_jsx("strong", { children: "Monitoring:" }), " ", opt.monitoring] }) })] }), opt.missingData.length > 0 && (_jsxs("div", { className: "treatment-missing", children: [_jsx("strong", { style: { fontSize: '0.75rem' }, children: "Missing data:" }), ' ', opt.missingData.join('; ')] })), _jsxs("details", { className: "treatment-section", style: { cursor: 'pointer' }, open: expandedCards[opt.id], onToggle: () => toggleExpand(opt.id), children: [_jsx("summary", { style: { fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-muted)' }, children: expandedCards[opt.id] ? 'Hide details' : 'Show details' }), _jsxs("div", { style: { marginTop: '0.5rem' }, children: [_jsx("h5", { children: "Comorbidity Considerations" }), _jsx("ul", { children: opt.comorbidityConsiderations.map((c, i) => _jsx("li", { children: c }, i)) })] })] })] }, opt.id))) }), _jsx(StepFooter, {})] }));
}
